addons:
  apt:
    packages:
      - aspell
      - aspell-en
  mysql: "5.7"
services:
    - postgresql
    - mysql
before_script:
    - psql -c 'create database test;' -U postgres
    - mysql -e 'create database test default character set utf8 default collate utf8_general_ci;'
language: perl
perl:
  - blead
  - dev
  - '5.30'
  - '5.28'
  - '5.26'
  - '5.24'
  - '5.22'
  - '5.20'
  - '5.18'
  - '5.16'
  - '5.14'
cache:
  directories:
    - $HOME/perl5
matrix:
  allow_failures:
    - perl: blead
  fast_finish: 1
  include:
    - env: COVERAGE=1
      perl: '5.30'
env:
  global:
    - AUTHOR_TESTING=1
    - RELEASE_TESTING=1
    - TEST_MYSQL=mysql://root@/test
    - TEST_POSTGRESQL=postgresql://postgres@/test
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto --always-upgrade-modules
### __app_cisetup__
# ---
# force_threaded_perls: 0
# perl_caching: 1

### __app_cisetup__
