addons:
  apt:
    packages:
      - aspell
      - aspell-en
  postgresql: 9.6
services:
    - postgresql
before_script:
    - psql -c 'create database test;' -U postgres
language: perl
perl:
  - '5.30'
  - '5.28'
  - '5.26'
  - '5.24'
  - '5.22'
  - '5.20'
  - '5.18'
  - '5.16'
  - '5.14'
cache:
  directories:
    - $HOME/perl5
env:
  global:
    - AUTHOR_TESTING=1
    - COVERAGE=1
    - RELEASE_TESTING=1
    - TEST_POSTGRESQL=postgresql://postgres@/test
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto --always-upgrade-modules
install:
  - cpanm -n Mojo::Pg
  - cpanm -n Mojo::mysql
### __app_cisetup__
# ---
# force_threaded_perls: 0
# perl_caching: 1

### __app_cisetup__
